# Generated by Django 5.1.6 on 2025-07-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorBoltGeoProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolt_diameter', models.CharField(max_length=50, verbose_name='Bolt Diameter')),
                ('bolt_diameter_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Bolt Diameter Value')),
                ('min_root_K', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Min.Root')),
                ('threads_per_inch', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Threads per Inch')),
                ('net_tensile_area_in2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Net Tensile Area, in2')),
                ('net_tensile_area_cm2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Net Tensile Area, cm2')),
                ('gross_bolt_area', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Gross Bolt Area')),
                ('min_root_area', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Min Root Area')),
                ('hex_f', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Hex F')),
                ('heavy_hex_f', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Heavy Hex F')),
                ('hex_abrg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Hex,Abrg')),
                ('heavy_hex_abrg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Heavy Hex,Abrg')),
            ],
            options={
                'verbose_name': '錨栓規格',
                'verbose_name_plural': '錨栓規格',
            },
        ),
    ]
