# Generated by Django 5.1.6 on 2025-07-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteelDesign', '0002_anchorboltmatproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteelMatProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_name', models.CharField(max_length=50, verbose_name='Material Name')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('unitweight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Unit Weight')),
                ('alpha', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True, verbose_name='Alpha')),
                ('E', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='E')),
                ('Fy', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Fy')),
                ('Ry', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ry')),
                ('Fu', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Fu')),
                ('Rt', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Rt')),
                ('rc_region', models.CharField(max_length=50, verbose_name='RC Region')),
            ],
            options={
                'verbose_name': '鋼材料規格',
                'verbose_name_plural': '鋼材料規格',
            },
        ),
        migrations.AlterModelOptions(
            name='anchorboltmatproperties',
            options={'verbose_name': '錨栓材料規格', 'verbose_name_plural': '錨栓材料規格'},
        ),
    ]
