# Generated by Django 5.1.6 on 2025-11-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='elementary_school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='畢業國小'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話'),
        ),
    ]
