# Generated by Django 5.1.6 on 2025-11-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_elementary_school_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased_modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
