# Generated by Django 5.1.6 on 2025-11-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_purchased_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purchased_modules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
