# Generated by Django 5.1.6 on 2025-11-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='商品名稱')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('prices', models.JSONField(default=dict, verbose_name='價格方案 (NT$)')),
            ],
        ),
    ]
