# Generated by Django 5.1.6 on 2025-11-15 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_trade_no', models.CharField(max_length=50, unique=True, verbose_name='綠界訂單號')),
                ('total_amount', models.IntegerField(verbose_name='總金額')),
                ('items', models.JSONField(verbose_name='商品項目')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已付款')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
        ),
    ]
